import { createContext, useContext, useMemo, useState, type ReactNode } from 'react';

export type Language = 'pt' | 'en' | 'fr';
const translations = {
  pt: { welcome: 'Bem-vindo de volta', loginSubtitle: 'Entra no teu espaço de comunicação.', username: 'Username', password: 'Password', login: 'Entrar', loggingIn: 'A entrar…', firstInstall: 'Primeira instalação? Usa admin / admin.', projectCredit: 'Criado por Martim', ownedConversations: 'Conversas que são realmente tuas.', openPlatform: 'Uma plataforma aberta para comunidades, equipas e amigos.', language: 'Idioma', settings: 'Definições', logout: 'Sair', channels: 'CANAIS', communitySpace: 'O teu espaço de comunidade', communityChat: 'Conversa da comunidade', callRoom: 'Sala de chamada', createServer: 'Criar servidor', createFirstServer: 'Cria o teu primeiro servidor', createFirstServerText: 'Organiza conversas, partilha ficheiros e inicia chamadas num espaço teu.', welcomeChannel: 'Este é o início do canal. Mantém a conversa útil e respeitosa.', messageTo: 'Mensagem para', protectAccount: 'Protege a conta principal', protectAccountText: 'Antes de continuar, substitui as credenciais iniciais. Esta etapa não pode ser ignorada.', newUsername: 'Novo username', newPassword: 'Nova password', passwordHint: 'Usa 10+ caracteres com maiúscula, minúscula, número e símbolo.', saveContinue: 'Guardar e continuar', globalAdmin: 'Administração global', users: 'Utilizadores', servers: 'Servidores', uploads: 'Uploads', createUser: 'Criar utilizador', createAccount: 'Criar conta', active: 'ativo', suspended: 'suspenso', enterCall: 'Entrar na chamada', callText: 'Confirma a qualidade e entra na sala. Podes alterar microfone e câmara depois.', quality: 'Qualidade', webRtcUnavailable: 'Este navegador não suporta chamadas WebRTC.' },
  en: { welcome: 'Welcome back', loginSubtitle: 'Sign in to your communication space.', username: 'Username', password: 'Password', login: 'Sign in', loggingIn: 'Signing in…', firstInstall: 'First installation? Use admin / admin.', projectCredit: 'Created by Martim', ownedConversations: 'Conversations that are truly yours.', openPlatform: 'An open platform for communities, teams, and friends.', language: 'Language', settings: 'Settings', logout: 'Sign out', channels: 'CHANNELS', communitySpace: 'Your community space', communityChat: 'Community conversation', callRoom: 'Call room', createServer: 'Create server', createFirstServer: 'Create your first server', createFirstServerText: 'Organize conversations, share files, and start calls in your own space.', welcomeChannel: 'This is the start of the channel. Keep the conversation useful and respectful.', messageTo: 'Message', protectAccount: 'Secure the main account', protectAccountText: 'Before continuing, replace the initial credentials. This step cannot be skipped.', newUsername: 'New username', newPassword: 'New password', passwordHint: 'Use 10+ characters with uppercase, lowercase, a number, and a symbol.', saveContinue: 'Save and continue', globalAdmin: 'Global administration', users: 'Users', servers: 'Servers', uploads: 'Uploads', createUser: 'Create user', createAccount: 'Create account', active: 'active', suspended: 'suspended', enterCall: 'Join call', callText: 'Confirm the quality and join the room. You can change your microphone and camera later.', quality: 'Quality', webRtcUnavailable: 'This browser does not support WebRTC calls.' },
  fr: { welcome: 'Bon retour', loginSubtitle: 'Connectez-vous à votre espace de communication.', username: "Nom d'utilisateur", password: 'Mot de passe', login: 'Se connecter', loggingIn: 'Connexion…', firstInstall: 'Première installation ? Utilisez admin / admin.', projectCredit: 'Créé par Martim', ownedConversations: 'Des conversations qui vous appartiennent vraiment.', openPlatform: 'Une plateforme ouverte pour les communautés, les équipes et les amis.', language: 'Langue', settings: 'Paramètres', logout: 'Déconnexion', channels: 'CANAUX', communitySpace: 'Votre espace communautaire', communityChat: 'Conversation de la communauté', callRoom: "Salle d'appel", createServer: 'Créer un serveur', createFirstServer: 'Créez votre premier serveur', createFirstServerText: 'Organisez des conversations, partagez des fichiers et lancez des appels dans votre espace.', welcomeChannel: 'Voici le début du canal. Gardez la conversation utile et respectueuse.', messageTo: 'Message pour', protectAccount: 'Sécurisez le compte principal', protectAccountText: "Avant de continuer, remplacez les identifiants initiaux. Cette étape ne peut pas être ignorée.", newUsername: "Nouveau nom d'utilisateur", newPassword: 'Nouveau mot de passe', passwordHint: 'Utilisez 10+ caractères avec majuscule, minuscule, chiffre et symbole.', saveContinue: 'Enregistrer et continuer', globalAdmin: 'Administration globale', users: 'Utilisateurs', servers: 'Serveurs', uploads: 'Téléversements', createUser: 'Créer un utilisateur', createAccount: 'Créer le compte', active: 'actif', suspended: 'suspendu', enterCall: "Rejoindre l'appel", callText: "Confirmez la qualité et rejoignez la salle. Vous pourrez modifier le micro et la caméra ensuite.", quality: 'Qualité', webRtcUnavailable: "Ce navigateur ne prend pas en charge les appels WebRTC." },
} as const;

type Key = keyof typeof translations.pt;
const Context = createContext<{ language: Language; setLanguage: (value: Language) => void; t: (key: Key) => string } | null>(null);
export function I18nProvider({ children }: { children: ReactNode }) {
  const detected: Language = navigator.language.startsWith('fr') ? 'fr' : navigator.language.startsWith('en') ? 'en' : 'pt';
  const [language, setState] = useState<Language>(() => (localStorage.getItem('webcord-language') as Language) || detected);
  const value = useMemo(() => ({ language, setLanguage: (next: Language) => { localStorage.setItem('webcord-language', next); document.documentElement.lang = next; setState(next); }, t: (key: Key) => translations[language][key] }), [language]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useI18n() { const value = useContext(Context); if (!value) throw new Error('Missing I18nProvider'); return value; }
export function LanguageSelect({ compact = false }: { compact?: boolean }) {
  const { language, setLanguage, t } = useI18n();
  return <label className={`language-select ${compact ? 'compact' : ''}`}><span>{t('language')}</span><select value={language} onChange={(event) => setLanguage(event.target.value as Language)}><option value="pt">Português</option><option value="en">English</option><option value="fr">Français</option></select></label>;
}
